name: omni-coveragereporter-lein

on:
  push:
    branches: [ main-DISABLE ]
  pull_request:
    branches: [ main-DISABLE ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: lein deps
    - name: Publish To Local Maven
      run: lein install
    - name: Run Tests
      run: lein test
    - name: Run Coverage
      run: lein with-profiles +coverage cloverage --lcov
    - name: Run Plugin
      run: lein with-profiles +run omni-coveragereporter-lein
